# Generated by Django 3.0.2 on 2020-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='标题')),
                ('Content', models.CharField(max_length=2000, verbose_name='内容')),
                ('Category', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'ordering': ('-Timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Menulist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=20, verbose_name='菜单标题')),
                ('MenuLogo', models.CharField(max_length=20, verbose_name='菜单图标')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
