# Generated by Django 3.0.2 on 2020-05-28 03:50

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutName', models.CharField(max_length=20, verbose_name='姓名')),
                ('Birthday', models.CharField(max_length=20, verbose_name='出生日期')),
                ('Nationality', models.CharField(max_length=20, verbose_name='国籍')),
                ('Introduce', models.CharField(max_length=500, verbose_name='介绍')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '自我介绍',
                'verbose_name_plural': '自我介绍',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='标题')),
                ('Content', models.CharField(max_length=2000, verbose_name='内容')),
                ('Category', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('url_height', models.PositiveIntegerField(default=165)),
                ('url_width', models.PositiveIntegerField(default=265)),
                ('Images', models.ImageField(blank=True, height_field='url_height', null=True, upload_to='images', verbose_name='图片', width_field='url_width')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ('-Timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Menulist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=20, verbose_name='菜单标题')),
                ('MenuLogo', models.CharField(max_length=20, verbose_name='菜单图标')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
                ('MenuUrl', models.CharField(max_length=200, verbose_name='菜单地址')),
            ],
            options={
                'verbose_name': '博客菜单',
                'verbose_name_plural': '博客菜单',
            },
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '图片标签',
                'verbose_name_plural': '图片标签',
                'ordering': ('-Timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='标题')),
                ('url_height', models.PositiveIntegerField(default=165)),
                ('url_width', models.PositiveIntegerField(default=265)),
                ('Images', models.ImageField(height_field='url_height', upload_to='images', verbose_name='图片', width_field='url_width')),
                ('avatar_thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.PhotoType')),
            ],
            options={
                'verbose_name': '图片分享',
                'verbose_name_plural': '图片分享',
                'ordering': ('-Timestamp',),
            },
        ),
    ]
