# Generated by Django 3.0.2 on 2020-05-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='Images',
            field=models.ImageField(upload_to='images', verbose_name='图片'),
        ),
    ]
