# Generated by Django 3.0.2 on 2020-04-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-Timestamp',), 'verbose_name': '博客文章', 'verbose_name_plural': '博客文章'},
        ),
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': '博客菜单', 'verbose_name_plural': '博客菜单'},
        ),
    ]
