# Generated by Django 3.0.2 on 2020-05-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20200528_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Images',
        ),
    ]
