# Generated by Django 3.0.2 on 2020-04-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_menulist_menuurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='MenuUrl',
            field=models.CharField(max_length=200, verbose_name='菜单地址'),
        ),
    ]
