# Generated by Django 3.0.2 on 2020-05-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200528_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Images',
        ),
    ]
