# Generated by Django 3.0.2 on 2020-04-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20200423_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, verbose_name='标题')),
                ('Images', models.CharField(max_length=2000, verbose_name='图片')),
                ('Category', models.CharField(blank=True, max_length=50, verbose_name='标签')),
                ('Timestamp', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '图片分享',
                'verbose_name_plural': '图片分享',
                'ordering': ('-Timestamp',),
            },
        ),
    ]
