# Generated by Django 3.0.2 on 2020-05-28 08:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_remove_blog_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='images'),
        ),
    ]
