# Generated by Django 3.0.2 on 2020-04-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_phototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.PhotoType'),
        ),
    ]
