# Generated by Django 3.0.2 on 2020-04-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20200424_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Images',
            field=models.ImageField(upload_to='images', verbose_name='图片'),
        ),
    ]
